spring:
  data:
    mongodb:
      username:
      password:
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.yadav.notification.kafka.OrderConfirmation, paymentConfirmation:com.yadav.notification.kafka.paymentConfirmation;
  application:
    name: notification-service

  mail:
    host: localhost
    port: 1025
    username: sachin
    password: sachin
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connetiontimeout: 5000
        timeout: 3000
        writetime: