create table category (
    id bigint generated by default as identity primary key,
    name varchar(255),
    description varchar(255)
);

create table product (
    id bigint generated by default as identity primary key,
    name varchar(255),
    description varchar(255),
--    available_quantity integer not null,
    available_quantity double precision not null,
    price numeric(38, 2),
    category_id bigint not null,
    constraint fk_product_category
        foreign key (category_id) references category(id)
);

--create sequence if not exists category_seq increment by 50;
--create sequence if not exists product_seq increment by 50;